channels:
  - conda-forge
  - tidair-tag
dependencies:
  - python
  - gcc_linux-64
  - gxx_linux-64
  - make
  - git
  - git-lfs
  - ipython
  - cmake
  - pyyaml
  - pyzmq
  - parse
  - click
  - numpy
  - pyqt
  - boost
  - bzip2
  - zeromq
  - sphinx
  - sphinx_rtd_theme
  - breathe
  - pyserial
  - p4p
  - sqlalchemy
  - pydm
  - matplotlib
  - rogue=v5.15.3
  - jupyterlab
  - simple-pid
