import pyrogue as pr


import warm_tdm

class TimingTx(pr.Device):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.add(pr.RemoteVariable(
            name = "Mode",
            description = "Select whether row-boundary events are generated by the hardware row-period timer or by the software strobe command.",
            offset = 0x18,
            bitSize = 1,
            bitOffset = 0,
            enum = {
                0: "Software",
                1: "Hardware"}))

        self.add(pr.RemoteCommand(
            name = "SoftRowStrobe",
            description = "Request a single software-driven row-boundary event when Mode is Software.",
            offset = 0x1C,
            bitSize = 1,
            bitOffset = 0,
            function = pr.RemoteCommand.touchOne))
        
#         self.add(pr.RemoteVariable(
#             name = 'EnOutput',
#             mode = 'RW',
#             offset = 0x30,
#             bitOffset = 0,
#             bitSize = 1,
#             base = pr.Bool))

        self.add(pr.RemoteVariable(
            name = "TxRefClkFreqRaw",
            description = "Measured transmit reference clock frequency in Hz.",
            mode = 'RO',
            offset = 0x60,
            bitOffset = 0,
            bitSize = 32,
            hidden = True))

        self.add(pr.LinkVariable(
            name = "TxRefClkFreq",
            description = "Measured transmit reference clock frequency in MHz.",
            mode = "RO",
            disp = '{:0.3f}',
            units = 'MHz',
            dependencies = [self.TxRefClkFreqRaw],
            linkedGet = lambda: self.TxRefClkFreqRaw.value()*1.0E-6))

        self.add(pr.RemoteVariable(
            name = "TxWordClkFreqRaw",
            description = "Measured timing word-clock frequency in Hz.",
            mode = 'RO',
            offset = 0x64,
            bitOffset = 0,
            bitSize = 32,
            hidden = True))

        self.add(pr.LinkVariable(
            name = "TxWordClkFreq",
            description = "Measured timing word-clock frequency in MHz.",
            mode = "RO",
            disp = '{:0.3f}',
            units = 'MHz',
            dependencies = [self.TxWordClkFreqRaw],
            linkedGet = lambda: self.TxWordClkFreqRaw.value()*1.0E-6))


        self.add(pr.RemoteCommand(
            name = 'StartRun',
            description = 'Start a timing run and prime the first pending row from RowIndexOrder[0].',
            offset = 0x00,
            bitOffset = 0,
            bitSize = 1,
            function = pr.Command.toggle))

        self.add(pr.RemoteCommand(
            name = 'EndRun',
            description = 'Request a clean end-of-run on the next row-boundary timeslot',
            offset = 0x04,
            bitOffset = 0,
            bitSize = 1,
            function = pr.Command.touchOne))

        self.add(pr.RemoteCommand(
            name = 'WaveformCapture',
            description = 'Request a waveform-capture timing marker at the programmed WaveformCaptureTime.',
            offset = 0x20,
            bitOffset = 0,
            bitSize = 1,
            function = pr.Command.touchOne))

        self.add(pr.RemoteVariable(
            name = 'WaveformCaptureTime',
            description = 'Row-time, in timing clocks from the most recent row boundary, at which WaveformCapture is emitted.',
            offset = 0x28,
            bitOffset = 0,
            bitSize = 32,
            disp = '{:d}'))

        self.add(pr.RemoteVariable(
            name = 'RowPeriodCycles',
            description = 'Number of timing-clock cycles in each row dwell period in hardware-timed mode.',
            mode = 'RW',
            offset = 0x08,
            bitOffset = 0,
            bitSize = 32,
            disp = '{:d}'))

        self.add(pr.LinkVariable(
            name = 'RowVisitRate',
            description = 'Effective row-boundary rate derived from RowPeriodCycles.',
            mode = 'RW',
            groups = ['NoConfig'],
            dependencies = [self.RowPeriodCycles],
            disp = '{:0.03f}',
            units = 'kHz (kRows/sec)',
            linkedGet = lambda read: 1.0e-3 / (max(float(self.RowPeriodCycles.get(read=read)), 1.0e-12) * 8.0e-9),
            linkedSet = lambda value, write: self.RowPeriodCycles.set(max(1, int(round(1.0 / ((float(value) * 1.0e3) * 8.0e-9)))), write=write)))

        self.add(pr.LinkVariable(
            name = 'RowVisitPeriod',
            description = 'Effective time between adjacent row-boundary events derived from RowPeriodCycles.',
            mode = 'RW',
            dependencies = [self.RowVisitRate],
            groups = ['NoConfig'],
            disp = '{:0.03f}',
            units = '\u03bcSec',
            linkedGet = lambda read: 1.0e3 / self.RowVisitRate.get(read=read),
            linkedSet = lambda value, write: self.RowVisitRate.set(1.0e-3 / value, write=write)))

        self.add(pr.RemoteVariable(
            name = 'NumRows',
            description = 'Number of entries in RowIndexOrder that participate in the active row sequence.',
            mode = 'RW',
            offset = 0x0C,
            bitOffset = 0,
            bitSize = 16,
            disp = '{:d}'))

        self.add(pr.LinkVariable(
            name = 'RowSequencePeriod',
            description = 'Time to complete one full pass through the programmed row sequence.',
            dependencies = [self.RowVisitPeriod, self.NumRows],
            disp = '{:0.03f}',
            units = '\u03bcSec',
            linkedGet = lambda read: self.RowVisitPeriod.get(read=read) * self.NumRows.get(read=read)))

        self.add(pr.LinkVariable(
            name = 'RowSequenceRate',
            description = 'Rate of full row-sequence wraps derived from RowSequencePeriod.',
            dependencies = [self.RowSequencePeriod],
            disp = '{:0.03f}',
            units = 'kHz',
            linkedGet = lambda read: 1.0e3 / max(self.RowSequencePeriod.get(read=read), 1.0e-12)))

        self.add(pr.RemoteVariable(
            name = 'RowSequencesPerDaqReadout',
            description = 'Number of RowSequences per DAQ readout',
            offset = 0x2C,
            bitSize = 32,
            disp = '{:d}'))

        self.add(pr.LinkVariable(
            name = 'DaqReadoutPeriod',
            description = 'Time between DAQ-readout-start boundaries derived from the row-sequence period and RowSequencesPerDaqReadout.',
            dependencies = [self.RowSequencePeriod, self.RowSequencesPerDaqReadout],
            disp = '{:0.03f}',
            units = '\u03bcSec',
            linkedGet = lambda read: self.RowSequencePeriod.get(read=read) * self.RowSequencesPerDaqReadout.get(read=read)))

        self.add(pr.LinkVariable(
            name = 'DaqReadoutRate',
            description = 'Rate of DAQ-readout-start boundaries derived from DaqReadoutPeriod.',
            dependencies = [self.DaqReadoutPeriod],
            disp = '{:0.03f}',
            units = 'Hz',
            linkedGet = lambda read: 1.0e6 / max(self.DaqReadoutPeriod.get(read=read), 1.0e-12)))
        
            

        self.add(pr.RemoteVariable(
            name = 'SampleStartTime',
            description = 'Row-time, in timing clocks from the most recent row boundary, at which the sample window begins.',
            mode = 'RW',
            offset = 0x10,
            bitOffset = 0,
            bitSize = 32,
            disp = '{:d}'))

        self.add(pr.RemoteVariable(
            name = 'SampleEndTime',
            description = 'Row-time, in timing clocks from the most recent row boundary, at which the sample window ends.',
            mode = 'RW',
            offset = 0x14,
            bitOffset = 0,
            bitSize = 32,
            disp = '{:d}'))

        self.add(pr.RemoteVariable(
            name = 'StageNextRowLead',
            description = 'Timing clocks before the next row boundary to stage the pending row',
            mode = 'RW',
            offset = 0x24,
            bitOffset = 0,
            bitSize = 32,
            disp = '{:d}'))

        self.add(pr.RemoteVariable(
            name = "PwrSyncEn",
            description = 'When set, sequence-start boundaries wait for the local PwrSync pulse before advancing.',
            mode = 'RW',
            offset = 0x1C,
            bitOffset = 1,
            bitSize = 1,
            base = pr.Bool,
            hidden = False))
        

        self.add(pr.RemoteVariable(
            name = 'PwrSyncA',
            description = 'Configure the PwrSyncA output level or oscillator mode generated by TimingTx.',
            offset = 0x80,
            bitOffset = 0,
            bitSize = 2,
            enum = {
                0: 'LOW',
                2: 'OSC'}))

        self.add(pr.RemoteVariable(
            name = 'PwrSyncB',
            description = 'Configure the PwrSyncB output level or oscillator mode generated by TimingTx.',
            offset = 0x80,
            bitOffset = 2,
            bitSize = 2,
            enum = {
                0: 'LOW',
                1: 'HIGH',
                2: 'OSC'}))

        self.add(pr.RemoteVariable(
            name = 'PwrSyncC',
            description = 'Configure the PwrSyncC output level or oscillator mode generated by TimingTx.',
            offset = 0x80,
            bitOffset = 4,
            bitSize = 2,
            enum = {
                0: 'LOW',
                1: 'HIGH',
                2: 'OSC'}))

        self.add(pr.RemoteVariable(
            name = 'SyncPeriodDiv2',
            description = 'Half-period divider used to generate the optional timing-domain power-sync oscillator outputs.',
            offset = 0x84,
            bitOffset = 0,
            bitSize = 32,
            disp = '{:d}'))

        self.add(pr.LinkVariable(
            name = 'SyncFrequency',
            description = 'Derived oscillator frequency for the power-sync outputs when configured for OSC mode.',
            dependencies = [self.SyncPeriodDiv2, self.TxWordClkFreqRaw],
            mode = 'RO',
            disp = '{:0.3f}',
            units = 'MHz',
            linkedGet = lambda read: 1.0e-6 * self.TxWordClkFreqRaw.get(read=read) / max(2*self.SyncPeriodDiv2.get(read=read), 1.0)))

        @self.command()
        def ResetSyncCounter():
            self.SyncPeriodDiv2.set(self.SyncPeriodDiv2.get(), write=True)

        self.add(pr.RemoteVariable(
            name = 'Running',
            description = 'Firmware run-state level. High while TimingTx is actively issuing timing events for a run.',
            mode = 'RO',
            offset = 0x30,
            bitOffset = 0,
            bitSize = 1,
            base = pr.Bool))

        self.add(pr.RemoteVariable(
            name = 'Sampling',
            description = 'Firmware sample-window level. High between SAMPLE_START and SAMPLE_END markers.',
            mode = 'RO',
            offset = 0x30,
            bitOffset = 1,
            bitSize = 1,
            base = pr.Bool))

        self.add(pr.RemoteVariable(
            name = 'RowSeq',
            description = 'Sequence index of the currently active row within RowIndexOrder.',
            mode = 'RO',
            offset = 0x34,
            bitOffset = 0,
            bitSize = 8,
            disp = '{:d}'))

        self.add(pr.RemoteVariable(
            name = 'RowIndex',
            description = 'Active physical row index currently in effect on the timing link.',
            mode = 'RO',
            offset = 0x34,
            bitOffset = 16,
            bitSize = 8,
            disp = '{:d}'))

        self.add(pr.RemoteVariable(
            name = 'RowIndexNext',
            description = 'Pending physical row index already prefetched for the next row-boundary commit.',
            mode = 'RO',
            offset = 0x34,
            bitOffset = 24,
            bitSize = 8,
            disp = '{:d}'))

        self.add(pr.RemoteVariable(
            name = 'RowTime',
            description = 'Timing-clock cycles elapsed since the most recent row-boundary event.',
            mode = 'RO',
            offset = 0x38,
            bitOffset = 0,
            bitSize = 32,
            disp = '{:d}'))

        self.add(pr.RemoteVariable(
            name = 'RunTime',
            description = 'Timing-clock cycles elapsed since the current run was started.',
            mode = 'RO',
            offset = 0x40,
            bitOffset = 0,
            bitSize = 64,
            disp = '{:d}'))

        self.add(pr.RemoteVariable(
            name = 'RowSeqCount',
            description = 'Count of completed full row-sequence wraps since StartRun.',
            mode = 'RO',
            offset = 0x70,
            bitOffset = 0,
            bitSize = 64,
            disp = '{:d}'))

        self.add(pr.RemoteVariable(
            name = 'DaqReadoutCount',
            description = 'Count of DAQ-readout-start boundaries emitted since StartRun.',
            mode = 'RO',
            offset = 0x78,
            bitOffset = 0,
            bitSize = 64,
            disp = '{:d}'))

        @self.command()
        def AnaPowerOff():
            self.PwrSyncB.set(1, write=False)
            self.PwrSyncC.set(0, write=False)
            self.writeBlocks()

        @self.command()
        def AnaPowerOn():
            self.PwrSyncB.set(0, write=False)
            self.PwrSyncC.set(1, write=False)
            self.writeBlocks()
        

        self.add(pr.RemoteVariable(
            name = 'XbarTxClkSrc',
            description = 'Select the clock source driven onto the timing crossbar TX clock path.',
            mode = 'RW',
            offset = 0x50,
            bitOffset = 0,
            bitSize = 1,
            enum = {
                0: 'RJ-45 RX',
                1: 'FPGA TX'}))


        self.add(pr.RemoteVariable(
            name = 'XbarRxClkSrc',
            description = 'Select the clock source driven onto the timing crossbar RX clock path.',
            mode = 'RW',
            offset = 0x50,
            bitOffset = 1,
            bitSize = 1,
            enum = {
                0: 'RJ-45 RX',
                1: 'FPGA TX'}))

        self.add(pr.RemoteVariable(
            name = 'XbarTxDataSrc',
            description = 'Select the data source driven onto the timing crossbar TX data path.',
            mode = 'RW',
            offset = 0x50,
            bitOffset = 4,
            bitSize = 1,
            enum = {
                0: 'RJ-45 RX',
                1: 'FPGA TX'}))


        self.add(pr.RemoteVariable(
            name = 'XbarRxDataSrc',
            description = 'Select the data source driven onto the timing crossbar RX data path.',
            mode = 'RW',
            offset = 0x50,
            bitOffset = 5,
            bitSize = 1,
            enum = {
                0: 'RJ-45 RX',
                1: 'FPGA TX'}))

        self.add(pr.RemoteVariable(
            name = 'XbarTxMgtSrc',
            description = 'Select the MGT source driven onto the timing crossbar TX MGT path.',
            mode = 'RW',
            offset = 0x50,
            bitOffset = 8,
            bitSize = 1,
            enum = {
                0: 'RJ-45 RX',
                1: 'FPGA TX'}))


        self.add(pr.RemoteVariable(
            name = 'XbarRxMgtSrc',
            description = 'Select the MGT source driven onto the timing crossbar RX MGT path.',
            mode = 'RW',
            offset = 0x50,
            bitOffset = 9,
            bitSize = 1,
            enum = {
                0: 'RJ-45 RX',
                1: 'FPGA TX'}))

        self.add(pr.RemoteVariable(
            name = 'XbarTxTimingSrc',
            description = 'Select the timing source driven onto the timing crossbar TX timing path.',
            mode = 'RW',
            offset = 0x50,
            bitOffset = 12,
            bitSize = 1,
            enum = {
                0: 'RJ-45 RX',
                1: 'FPGA TX'}))


        self.add(pr.RemoteVariable(
            name = 'XbarRxTimingSrc',
            description = 'Select the timing source driven onto the timing crossbar RX timing path.',
            mode = 'RW',
            offset = 0x50,
            bitOffset = 13,
            bitSize = 1,
            enum = {
                0: 'RJ-45 RX',
                1: 'FPGA TX'}))


        self.add(pr.RemoteVariable(
            name = 'RowIndexOrder',
            description = 'Row-order RAM contents indexed by RowSeq; each entry provides the physical RowIndex to activate for that sequence slot.',
            offset = 0x1000,
            valueBits = 8,
            numValues = 256,
            valueStride = 32,
            base = pr.UInt,
            mode = 'RW'))
