# Warm TDM; subject to LICENSE.txt in the repository root.
export REMOVE_UNUSED_CODE = 0
export PRJ_VERSION = 0x00000001
export PRJ_PART = XC7K325TFFG676-2
target: xsim
include ../../submodules/ruckus/system_vivado.mk
