SET (S4DAQSender_FIND_QUIETLY TRUE)
SET (S4DAQSender_FIND_REQUIRED TRUE)

IF(NOT S4DAQSender_FOUND)
	FIND_PATH(S4DAQSender_INCLUDE_DIR s4daq/rogue_data_sender.h
              PATHS $ENV{S4DAQSenderROOT}/include
              NO_DEFAULT_PATH)
    FIND_PATH(S4DAQSender_INCLUDE_DIR s4daq/rogue_data_sender.h)
    if(S4DAQSender_INCLUDE_DIR)
		SET(S4DAQSender_INCLUDE_DIR "${S4DAQSender_INCLUDE_DIR}" CACHE PATH "Path to S4DAQSender headers" FORCE)
	endif()
	FIND_LIBRARY(S4DAQSender_LIBRARIES NAMES s4daq_sender
	             PATHS $ENV{S4DAQSenderROOT}/lib
	             NO_DEFAULT_PATH)
	FIND_LIBRARY(S4DAQSender_LIBRARIES NAMES s4daq_sender)
	GET_FILENAME_COMPONENT(S4DAQSender_LIB_DIR ${S4DAQSender_LIBRARIES} PATH)
	INCLUDE (FindPackageHandleStandardArgs)
	FIND_PACKAGE_HANDLE_STANDARD_ARGS(S4DAQSender DEFAULT_MSG S4DAQSender_LIBRARIES S4DAQSender_INCLUDE_DIR)
	
	if(S4DAQSender_FOUND)
		SET(S4DAQSender_INCLUDE_DIRS "${S4DAQSender_INCLUDE_DIR}" CACHE PATH "Path to S4DAQSender headers" FORCE)
		SET(S4DAQSender_LIBRARIES "${S4DAQSender_LIBRARIES}" CACHE PATH "S4DAQSender libraries" FORCE)
		SET(S4DAQSender_CXXFLAGS "-I${S4DAQSender_INCLUDE_DIR}")
		SET(S4DAQSender_LDFLAGS "${S4DAQSender_LIBRARIES}")
		MESSAGE(STATUS "Found S4DAQSender:")
		MESSAGE(STATUS "  * includes: ${S4DAQSender_INCLUDE_DIR}")
		MESSAGE(STATUS "  * libs:     ${S4DAQSender_LIBRARIES}")
	endif()
ENDIF(NOT S4DAQSender_FOUND)