
# Define target output
target: prom

# Define target part
export PRJ_PART = XC7K160TFBG484-1

export RUCKUS_DIR = $(abspath $(PWD)/../../submodules/ruckus)

#export REMOVE_UNUSED_CODE = 1

export PRJ_VERSION = 0x00000000

export GIT_BYPASS = 1

# Use top level makefile
include $(RUCKUS_DIR)/system_vivado.mk



