export GIT_BYPASS = 1

# Define target part
export PRJ_PART = xcau25p-sfvb784-1-e

# Using a non-standard target name
export TARGET = ColumnAu25p

target: bit

export TOP_DIR = $(abspath $(PWD)/../..)
export PRJ_VERSION = 0x00000001

include $(TOP_DIR)/submodules/ruckus/system_vivado.mk
