#!/usr/bin/env python3
#-----------------------------------------------------------------------------
# Title      : 
#-----------------------------------------------------------------------------
# Description:
# Script to quickly test rogue devices
#-----------------------------------------------------------------------------
# This file is part of the HPS project. It is subject to 
# the license terms in the LICENSE.txt file found in the top-level directory 
# of this distribution and at: 
#    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html. 
# No part of the HPS project, including this file, may be 
# copied, modified, propagated, or distributed except according to the terms 
# contained in the LICENSE.txt file.
#-----------------------------------------------------------------------------
import time
import argparse
import glob
import os
import sys
import importlib

import pyrogue
import rogue

# Search paths
if '--local' in sys.argv:
    baseDir = os.path.dirname(os.path.realpath(__file__))
    pyrogue.addLibraryPath(f'{baseDir}/../../firmware/python')
    pyrogue.addLibraryPath(f'{baseDir}/../python')    
    pyrogue.addLibraryPath(f'{baseDir}/../../firmware/submodules/surf/python')

import warm_tdm
import warm_tdm_api

#rogue.Logging.setFilter('pyrogue.SrpV3', rogue.Logging.Debug)
#rogue.Logging.setFilter('pyrogue._Device', rogue.Logging.Info)

# Set the argument parser
parser = warm_tdm_api.WarmTdmArgparse()

parser.add_argument(
    "--path", '-p',
    type     = str,
    required = False,
    default = None,
    help     = "path to image",
)

parser.add_argument(
    "--reload", '-r',
    action   = 'store_true',
    help     = "after programming the PROM, reload (reboot) that board's FPGA from PROM",
)

parser.add_argument(
    "--reload-only", '-R',
    action   = 'store_true',
    help     = "skip programming; only reload (reboot) a board's FPGA from PROM",
)

args = parser.parse_known_args()[0]
print(args)

arg_dict = warm_tdm_api.arg_dict(args)
arg_dict['pollEn'] = False
arg_dict['initRead'] = False

with warm_tdm_api.GroupRoot(**arg_dict) as root:

#     devs = root.find(name='WarmTdmCore')
#     for d in devs:
#         d.enable.set(False)
    
    print('Finding and reading group')

    avs = root.find(name='AxiVersion')

    print('Found the following boards')
    for i, av in enumerate(avs):
        print(f'Board {i} - {av.path}')
        av.readBlocks()
        av.waitBlocks()
        av.printStatus()
        print()

    def reload_fpga(av):
        # FpgaReload is a posted write (no response is expected): the FPGA
        # reboots from the PROM and the SRP link drops, so this is necessarily
        # the last transaction we issue on that board.
        print(f'Reloading FPGA from PROM via {av.path} '
              '(the FPGA will reboot and the link will drop)...')
        av.FpgaReload()

    # Stand-alone reload: skip programming entirely, just reboot a board (or all
    # boards) from whatever image is already in its PROM.
    if args.reload_only:
        sel = input("Select which board's FPGA to reload [index or 'all']: ").strip()
        targets = avs if sel == 'all' else [avs[int(sel)]]
        x = input(f'Reload {len(targets)} FPGA(s) from PROM [y]/n: ')
        if x == 'n':
            exit()
        for av in targets:
            reload_fpga(av)
        exit()

    proms = root.find(name='AxiMicronN25Q')

    print('Found the following PROMs')

    for i, prom in enumerate(proms):
        print(f'{i} - {prom.path}')

    idx = int(input('Select which PROM you wish to flash: '))
   
    prom = proms[idx]
    prom.enable.set(True)

    if args.path is None:
        BasePackage = importlib.import_module('warm_tdm')
        args.path = BasePackage.ImageDir
    
    if os.path.isdir(args.path):
        # Get a list of images
        images = glob.glob('{}/*.mcs*'.format(args.path))
        images = list(reversed(sorted(images)))

        for i, l in enumerate(images):
            print('{} : {}'.format(i, l))

        idx = int(input('Enter image for flash: '))
        image = images[idx]
    else:
        image = args.path


    print(f'Loading {image} to {prom.path}')
    x = input('Are you sure you wish to procede [y]/n: ')
    if x == 'n':
        exit()
        
    print(f'Loading MCS file: {image}')
    prom.LoadMcsFile(image)

    # Optionally reboot the just-programmed board from its new PROM image. The
    # PROM and the AxiVersion are siblings on the same board (WarmTdmCommon), so
    # the board to reload is simply the flashed PROM's sibling AxiVersion.
    if args.reload:
        av = getattr(prom.parent, 'AxiVersion', None)
        if av is None:
            found = prom.parent.find(name='AxiVersion')
            av = found[0] if found else None
        if av is None:
            print(f'WARNING: no AxiVersion found alongside {prom.path}; cannot '
                  'reload. Power-cycle the board or rerun with --reload-only.')
        else:
            reload_fpga(av)

exit()


