# ----------------------------------------------------------------------------
# Title      : WarmTDM GitHub Actions Script
# ----------------------------------------------------------------------------
# This file is part of the WarmTDM software package. It is subject to
# the license terms in the LICENSE.txt file found in the top-level directory
# of this distribution and at:
#    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html.
# No part of the WarmTDM software package, including this file, may be
# copied, modified, propagated, or distributed except according to the terms
# contained in the LICENSE.txt file.
# ----------------------------------------------------------------------------
# The following environment variables are required for this process:
# secrets.GH_TOKEN

name: WarmTDM Integration
on: [push]

jobs:

  test_and_document:
    name: Test And Generate Documentation
    runs-on: ubuntu-20.04
    steps:

      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install -r pip_requirements.txt

      - name: Python Syntax Check
        run: |
          python -m compileall -f software/python/
          python -m compileall -f firmware/python/
          #flake8 --count software/python/
          #flake8 --count firmware/python/

      - name: Generate Documentation
        if: github.ref == 'refs/heads/main'
        run: |
          cd docs
          make html

      - name: Deploy Documentation
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: docs/build/html

